# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pr: none

variables: 
- group: nexus-snapshot-repository

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: Daily Snapshot Publish
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-DskipITs -s .maven/settings.xml -DaltDeploymentRepository=nexus-snapshots::default::https://oss.sonatype.org/content/repositories/snapshots/ -pl !azure-spring-boot-samples,!azure-spring-boot-tests'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean deploy'